### ISSUE TITLE
Atom One Dark code sample theme not working

### ISSUE THREAD

**Issue by mdentinho** [NoDivide/astrum#102]
#### Tell us about the issue you are experiencing
When setting the `code_highlight_theme` to hightlight.js‘ `atom-one-dark` style option,  the style is not applied and the code sample get messed up.

#### What behaviour would you expect?
It should load the style and apply it to the code sample.

#### How can this issue be replicated?
1. Change the `code_highlight_theme` value on `data.json` to `atom-one-dark`.
2. Make sure you have a component with code sample defined.
3. Open the library pattern on the browser.
4. Click on "Show Code Sample" from any component to see the messed up code sample (better viewed with a dark background).
5. Open the browsers Console to check the http request error.

#### Screenshots / Screencast
<img width="809" alt="screen shot 2017-03-05 at 08 37 14" src="https://cloud.githubusercontent.com/assets/210138/23585409/f8adbe8c-017e-11e7-9f72-e06c4a7d0822.png">
<img width="776" alt="screen shot 2017-03-05 at 08 38 38" src="https://cloud.githubusercontent.com/assets/210138/23585414/3d50d81c-017f-11e7-8690-bcdffb3a4cfa.png">

#### Your environment
Platform: macOS
OS Version: 10.12.3
Node Version: 6.9.4
NPM Version: 4.1.1
Astrum Version: 1.9.3

**Comment by mdentinho** [comment]
FYI: I was not able to apply the `bug` label as requested in the Contributing instructions.

**Comment by gethinoakes** [comment]
👍  same issue

**Comment by RyanHavoc** [comment]
@mdentinho @gethinoakes Hi guys. I've just release a fix for this in v1.9.4. Basically the atom-one-dark theme wasn't available in highlight.js 9.3.0 so I've upgrade Astrum to 9.12.0.

Note that you'll want to set the `override_code_highlight_bg` to null to use the themes default background.
