### ISSUE TITLE
Changing library_title doesn‘t apply to all instances of 'Pattern Library'.

### ISSUE THREAD

**Issue by mdentinho** [NoDivide/astrum#104]
#### Tell us about the issue you are experiencing
The loading message, the page‘s title and the creators list (on the copyright section) are using a hardcoded `Pattern Library` text. If I want to call my library something else, it would still show `Pattern Library` on those instances.

#### What behaviour would you expect?
When changing the `theme`>`titles`>`library_title` value from `Pattern Library` to something else, the value should be applied to all instances of the 'Pattern Library' text.

#### How can this issue be replicated?
1. Edit `theme`>`titles`>`library_title` on `data.json` to anything other than `Pattern Library`.
2. Make sure you have a component defined.
3. Open the library pattern on the browser.
4. While loading, the loading message is still showing 'Building **_library pattern_**'. After loading, the page‘s title and the creators list (on the copyright section) still show 'Pattern Library'.

#### Screenshots / Screencast
![ruiuzpjgdoyhlae_vpchfsjhm0ompzxho-oh0cwqzr8xukbgr0t2tv6ogda5lssgziwwvkcceludhaepmn4hzfnlsmh0egfbdyhze6lvomai4av1wcwksmudutgzhrrg](https://cloud.githubusercontent.com/assets/210138/23585960/6ebb4aac-018b-11e7-8ca8-204d0295c3dc.gif)

#### Your environment

Platform: macOS
OS Version: 10.12.3
Node Version: 6.9.4
NPM Version: 4.1.1
Astrum Version: 1.9.3

**Comment by mdentinho** [comment]
I can send a PR for this as soon as it is accepted.

**Comment by RyanHavoc** [comment]
@mdentinho Good spot. This does need updating. I'll address it in the next release.

**Comment by hankchizljaw** [comment]
PR with fix created (#148). Nice catch, @mdentinho 🙂
