### ISSUE TITLE
Question: Groups for content pages

### ISSUE THREAD

**Issue by mischah** [NoDivide/astrum#107]
I’m not sure if I just don’t see the option. I open an issue because I didn’t found a Link to a Gitter Room or something.

Question:
Am I right that I can only add pages to one one navigation section like described here?
https://github.com/NoDivide/astrum#content-pages

Wouldn’t it be awesome to be able to group them like we can group components?

Use case: 
Showcase different pages with combinations of components.

**Comment by RyanHavoc** [comment]
@mischah The pages section is intended for documentation e.g. coding conventions, read me's, introductory copy etc. Not for fully rendered templates of components. Does that make sense?

**Comment by mischah** [comment]
> The pages section is intended for documentation e.g. coding conventions, read me's, introductory copy etc. Not for fully rendered templates of components. Does that make sense?

Jup. 


But I would love to create some example pages which do combine multiple components. 
Like Pattern Lab does over here: http://demo.patternlab.io/?p=pages-homepage

Please note that I don’t feel the need for the whole »atoms«, »molecules«, »organism« approach.

I just need »components« and »pages« (to showcase how components should be combined).

And that need would be fulfilled with with the ability to group pages.

## Possible solution 1

```JSON
    "content": {
        "show_first_page_on_load": true,
        "groups": [
            {
                "title": "Overview",
                "pages": [
                    {
                        "name": "introduction",
                        "title": "Introduction",
                        "file": "./pages/intro.md"
                    }
                ]
            },
            {
                "title": "Example pages",
                "pages": [
                    {
                        "name": "signup",
                        "title": "Signup Form",
                        "file": "./pages/forms/signup.html"
                    },
                    {
                        "name": "contact",
                        "title": "Contact Form",
                        "file": "./pages/forms/contact.html"
                    }
                ]
            }
        ]
    }
```

### This could be rendered as:

<img src="https://cloud.githubusercontent.com/assets/441011/23633411/eabb6656-02c5-11e7-98c4-dda597dfdd0d.png" width="258">

## Possible solution 2

```json
    "content": {
        "show_first_page_on_load": true,
        "title": "Pages",
        "groups": [
            {
                "title": "Overview",
                "pages": [
                    {
                        "name": "introduction",
                        "title": "Introduction",
                        "file": "./pages/intro.md"
                    }
                ]
            },
            {
                "title": "Forms examples",
                "pages": [
                    {
                        "name": "signup",
                        "title": "Signup Form",
                        "file": "./pages/forms/signup.html"
                    },
                    {
                        "name": "contact",
                        "title": "Contact Form",
                        "file": "./pages/forms/contact.html"
                    }
                ]
            }
        ]
    }
```

### This could be rendered as:

<img src="https://cloud.githubusercontent.com/assets/441011/23633866/baa32876-02c7-11e7-8c62-e726e8218db2.png" width="264">

----


Would you accept a pull request which implements that?

**Comment by mdentinho** [comment]
@mischah I would say that in your case they are components and not pages.

A `Sign Up Form` and a `Contact Form` are just components made out of other smaller components. I think that this is the way things are being shaped for the web now and how `Web Components` will work.

In any case, I also feel the need to maybe split some components of different types in separated categories, but I‘d say that it would be easier to implement and make more sense to have it applied to the components structure instead of changing how the pages structure work, since they have another purpose, as explained by @RyanHavoc.

So, using your first solution as reference, my suggestion is that the current `data.json` structure for components would changed from this:
```json
"groups": [
  {
    "name": "group-one",
    "title": "Group 1",
    "components": [
      {<current-component-config-object>},
      {<current-component-config-object>}
    ]
  },
  {
    "name": "group-two",
    "title": "Group 2",
    "components": [
      {<current-component-config-object>},
      {<current-component-config-object>}
    ]
  },
]
```

To this:
```json
"components": [
  {
    "category-name": "simple-components",
    "category-title": "Simple Components",
    "groups": [
      <current-group-config-object>,
      <current-group-config-object>
    ]
  },
  {
    "category-name": "example-pages",
    "category-title": "Example Pages",
    "groups": [
      <current-group-config-object>,
      <current-group-config-object>
    ]
  },
]
```

Which would render as:
<img width="266" alt="screen shot 2017-03-07 at 12 12 54" src="https://cloud.githubusercontent.com/assets/210138/23654088/731b16d6-032f-11e7-8f6f-e2d7584b87db.png">

This seems to make more sense for me and also that it is more doable.

**Comment by mischah** [comment]
Thanks a bunch 💖 

This totally makes sense 👌 

Cheers, Michael

**Comment by tharakanilupul** [comment]
Hi mdentinho,

I also used to grouping components such as Atomic Component, Molecular Component. I have tried to go with you solution, but still stuck with it.

Can you provide sample data.json file for above changes.

Cheers, Tharaka
