### ISSUE TITLE
Init error "ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by rahcon** [NoDivide/astrum#11]
I tried to initialize astrum as recommended. But everytime I try to init I run into this error:
`Error: Error: ENOENT: no such file or directory, lstat '/Users/-/${HOME}/.npm-packages/lib/node_modules/astrum/_template'
/Users/-/.npm-packages/lib/node_modules/astrum/manager/utils.js:31
            throw(new Error(chalk.red("No data.json file found in " + _this.$config.path )));
Error: No data.json file found in ./pattern-library
    at Object.module.exports.init (/Users/-/.npm-packages/lib/node_modules/astrum/manager/utils.js:31:19)
    at /Users/-/.npm-packages/lib/node_modules/astrum/manager/utils.js:58:27
    at /Users/-/.npm-packages/lib/node_modules/astrum/node_modules/fs-extra/lib/copy/copy.js:23:21
    at FSReqWrap.oncomplete (fs.js:82:15)` 
My System:
Mac OS X El Capitan 10.11.4
Node 4.4.7
NPM 3.10.3

**Comment by matt-west** [comment]
Thanks for reporting this @rahcon. It appears that this is an issue when running Astrum under Node 4.4.7. I've tested with 4.4.5 and it's working correctly.

I'll look into this further and get back to you.

**Comment by matt-west** [comment]
@rahcon Can you please try updating to the latest version of Astrum (1.5.10). It looks like this bug may have already been fixed.
