### ISSUE TITLE
Need to add an overwrite for link styling in your own css

### ISSUE THREAD

**Issue by welcomebrand** [NoDivide/astrum#113]
#### Tell us about the issue you are experiencing
Our own css uses background-image for link underlines and when I attach our css file to the library this applies it to all your library links too causing an un-needed underline on everything. 

#### What behaviour would you expect?
No underlines from background-image styles. Just needs overwriting in your own css. 

#### How can this issue be replicated?
In your own css (project, not astrum) you could add our website styling for links and should be able to replicate. 
`a {
    text-shadow: 3px 0 0 #fff, -3px 0 0 #fff;
    background-image: linear-gradient(to left, #4E514E, #4E514E);
    background-position: 0 97%;
    background-repeat: repeat-x;
    background-size: 1px 1px;
    text-decoration: none;
    color: #4E3D42;
}`

#### Screenshots / Screencast
![capture](https://cloud.githubusercontent.com/assets/337631/24208803/74e0556e-0f1c-11e7-81b5-06dbc5e6e030.PNG)

#### Your environment

Platform: Windows
OS Version: 10
Node Version: 
NPM Version: 
Astrum Version:

**Comment by RyanHavoc** [comment]
@welcomebrand The current `release\2.0.0` of Astrum has additional features to prevent style conflicts between Astrum and project styles. It's still in development but it should fix this issue.
