### ISSUE TITLE
Remove external dependencies

### ISSUE THREAD

**Issue by laitine** [NoDivide/astrum#114]
I think the external dependencies should be included internally or optionally this could be configured in the data.json. This is is a requirement for most strict deploy environments but also would make the static assets more self-contained IMHO. There is now the "font_libraries" option but regardless the index.html template includes the following dependencies by default.

```
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
        <script>
            WebFont.load({
                google: {
                    families: ['Open Sans']
                }
            });
        </script>
```

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.25/vue.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.8.0/vue-resource.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/10.0.0/js/smooth-scroll.min.js"></script>
```

**Comment by RyanHavoc** [comment]
@laitine The dependencies will be internal in version 2.0. This has already been applied on the release/2.0.0 if you want to experiment: https://github.com/NoDivide/astrum/tree/release/2.0.0

**Comment by laitine** [comment]
Great, thanks!
