### ISSUE TITLE
".ndpl-components " container stretches over 'pages'

### ISSUE THREAD

**Issue by martin-strohsal** [NoDivide/astrum#115]
#### Tell us about the issue you are experiencing

When opening one of the 'pages', a random (!) .ndpl-components container stretches over the content of the 'pages' content. It seems to have something to do with the 'preload' class. Preloaded elements seem to be hidden by positioning them -9999px in x- and y-directions. The container stretches to full width anyway, laying itself over the contents of the 'pages', so that e.g. the links on the page are no longer clickable.

It MAY have something to do with our own CSS, but since it is a random .ndpl-components container stretching out, I doubt it. Also, there are no fany css-tricks used from out side.

Side note: No errors are thrown in the console.

Side note: We have configured around five groups with nearly twenty components in total. Maybe too much?

Anyway, help is much appreciated!

Thank you.

#### What behaviour would you expect?

That I can see / interact with the contents of the 'pages'.

#### How can this issue be replicated?

Good question. 

#### Screenshots / Screencast

![desktop](https://cloud.githubusercontent.com/assets/751859/25092572/9781f402-238e-11e7-898e-6c24b3e197a6.png)

I gave the erroneous container a half transparent inline background color to display the error.

#### Your environment

Platform: Ubuntu, MacOS
OS Version: Ubuntu 16.04, MacOS 10.12.14
Node Version: 4.2.6
NPM Version: 4.0.3
Astrum Version: 1.9.3

**Comment by RyanHavoc** [comment]
@martin-strohsal Any way I can access your library to review this issue?

**Comment by martin-strohsal** [comment]
Sadly, there is no way at the moment -NDA ftw.

**Comment by RyanHavoc** [comment]
@martin-strohsal Apologies for the long delay in getting back to you with this. `release/2.0.0` approaches Astrum rendering a bit differently now. You may want to give it a try and see if it fixes your issue (if it's still an issue...)?
