### ISSUE TITLE
Is it possible to install astrum as dev-dependency and not globally?

### ISSUE THREAD

**Issue by Gonzalo2683** [NoDivide/astrum#116]
#### Tell us about the issue you are experiencing

I have installed astrum as dev-dependency and I have configured an npm script:
```
....
 "astrum": "astrum"
....
```
I have run `npm run astrum init ./public/library` but I get an error:

> No astrum-config.json file found in project root

#### What behaviour would you expect?
How can i use astrum as a local dependency?

#### Your environment
I use nodist to manage different node versions.

Platform: windows
OS Version: 7
Node Version: v6.9.4
NPM Version: 4.0.5
Astrum Version: ^1.9.3

**Comment by giothevanni** [comment]
This issue actually relates and gets fixed with a currently open pull request (#96).
