### ISSUE TITLE
Environment specific stylesheet URL

### ISSUE THREAD

**Issue by dnlmzw** [NoDivide/astrum#127]
I'd like to be able to specify stylesheet URL based on my current environment (development, staging, production).

It would be great if I could use environment variables in the data.json file understand what alternative way I should achieve this. I can't currently find any best-practice guidance in previous issues or the documentation.

My URLs are:
http://localhost:3000/assets/application.css
https://domain.com/assets/application.css

Background:
I don't want to add Astrum to my main repo, but instead want to reference my primary stylesheet and run it as a seperate server.

OBS: I read the CONTRIBUTING.md but couldn't figure out how to add label "feature request". Will edit this issue if someone can guide me in the right direction.

**Comment by RyanHavoc** [comment]
@dnlmzw So do you plan on have a single instance of Astrum or multiple (one for each environment)? For example are you going to have a Production instance that reflects your live site and a Local instance that's your work in progress?

**Comment by RyanHavoc** [comment]
@dnlmzw I'm going to close these issue seen as I haven't heard back from you. If you'd like to discuss further feel free to reopen it.
