### ISSUE TITLE
Demo as standalone repository

### ISSUE THREAD

**Issue by NicoMai** [NoDivide/astrum#13]
Great work and you have a wonderful Demo to view.

Is it possible that the Demo gets an own repository here on github to view the source of the Demo as an example to use Astrum?

**Comment by RyanHavoc** [comment]
@NicoMai Thanks. The demo's already in the repo: https://github.com/NoDivide/astrum/tree/gh-pages/pattern-library 😀

**Comment by NicoMai** [comment]
@RyanHavoc Thanks. That's another branch, so i can't see it in the "normal" fork.
