### ISSUE TITLE
2.0 status

### ISSUE THREAD

**Issue by ryzy** [NoDivide/astrum#133]
Hi,

I'm starting new project and thinking about using Astrum (looks awesome, great job BTW!). Because it's a new project, it'd probably make sense to start it with newer 2.0 version (now beta).

I see we have 2.0.0 branch, but not so much traffic there. Any update on status of 2.0?

What do you think, is 2.0 stable enough to use it commercial company project? Also, I didn't see any material about what new goodies it does bring to play - any pointers here?

Thanks!
Marcin

**Comment by RyanHavoc** [comment]
Hi @ryzy,

Release 2.0 should be pretty stable at this point. Best to look at the commit history for that branch to see what's been added so far. Unfortunately I don't have an ETA for when 2.0 will be ready. I'm working on it as and when I have time at the moment. :-(

**Comment by ryzy** [comment]
Thanks @RyanHavoc , keep up with that good work!
