### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by ricricucit** [NoDivide/astrum#138]
#### Tell us about the issue you are experiencing
The link to the [development roadmap](https://trello.com/b/HVvM0YAb/astrum-development-roadmap) doesn't work. It's probably because the board is set to "private"

#### What behaviour would you expect?
See the dev roadmap.

#### How can this issue be replicated?
Click [here](https://trello.com/b/HVvM0YAb/astrum-development-roadmap) and open with an "incognito window".

#### Screenshots / Screencast
<img width="785" alt="screen shot 2017-10-01 at 17 52 56" src="https://user-images.githubusercontent.com/1016775/31056407-6a2c0832-a6d1-11e7-8fd7-5da9755bb8ef.png">

#### Your environment

Doesn't matter :)

**Comment by RyanHavoc** [comment]
@ricricucit You must have an old link saved. The development roadmap has been moved: https://github.com/NoDivide/astrum/projects/2

**Comment by ricricucit** [comment]
Thanks!
JFYI: the link comes from [your wiki](https://github.com/NoDivide/astrum/wiki).
