### ISSUE TITLE
Add option to set a component's display order as "last" on create/edit

### ISSUE THREAD

**Issue by hankchizljaw** [NoDivide/astrum#141]
One thing I've found while working with Astrum is that I normally want a new component to appear at the bottom of the collection. 

Just as there's an option to set the display order as "first" on create/edit, it'd be great to also be able to set it as "last".

**Comment by RyanHavoc** [comment]
But it defaults to last...? When you get to that position option it should say something like “Position after x component” by default and if you just go with that it will appear last in the collection.

**Comment by hankchizljaw** [comment]
True, but you have to choose an option don't you? Because of that, you have to find the last component in the list to set your new one as last. It took me a few runs to notice that pressing the up key selects the last component in the collection, even though the helper text tells you that you can. 

You could write that off as me being bone-idle though 😂

**Comment by RyanHavoc** [comment]
I’m going to have to double check this in the morning. The components listed should be in the order they appear in the collection with the one selected being the last one therefore the new component becoming the last one automatically... 😕

**Comment by hankchizljaw** [comment]
Sorry man, but "first" is selected by default. The components are in the correct order though. 

Check out this GIF: 
![astrum](https://user-images.githubusercontent.com/8672583/31688266-c5dcd666-b383-11e7-92ab-8a03f507fc9e.gif)

**Comment by hankchizljaw** [comment]
I think whether it’s currently in place or not, the behaviour you described is better than a “last” option. I think “Position after X” being selected with X being the last one is clearer.

**Comment by RyanHavoc** [comment]
This actually won't be too difficulty to switch. I'll add it to the roadmap for release/2.0.0. Good catch!

**Comment by hankchizljaw** [comment]
🚀

**Comment by hankchizljaw** [comment]
Fix added in #146
