### ISSUE TITLE
upgrading to release/2.0.0 ?

### ISSUE THREAD

**Issue by rossmc** [NoDivide/astrum#151]
#### Tell us about the issue you are experiencing
Just a couple of questions...

1. Will version 2 be compatible with version 1?
2. How can I upgrade to release/2.0.0?

#### Your environment

Platform:
OS Version: OSX v 10.12.6
Node Version: v6.11.3
NPM Version: 5.3.0
Astrum Version: 1.9.5

**Comment by hankchizljaw** [comment]
Hey Ross,

Here's your answers:
1. We'll be working hard to make sure there are very few, if any breaking changes in version 2. We certainly don't want to make it difficult to upgrade.
2. The `release/2.0.0` branch is a pre-release, work in progress branch. You can use it though by checking it out and then running `npm link` inside of the `astrum` directory.

I hope that helps!
