### ISSUE TITLE
'index.html' not loading in Chrome

### ISSUE THREAD

**Issue by nadalsol** [NoDivide/astrum#155]
#### Tell us about the issue you are experiencing

I'm trying to open the `index.html` file from Chrome, though I'm getting a permanent "Building pattern library..." message (pattern library doesn't get loaded).

Besides, I'm getting several error messages in the JS console:

![screen shot 2018-01-23 at 13 21 42](https://user-images.githubusercontent.com/3439783/35275784-22bc5f78-0041-11e8-8ad2-8b4401c385a2.png)

The curious thing is that it works fine in Firefox.

#### What behaviour would you expect?

Pattern library should work properly for every browser (including Chrome), when openeing `index.html`.

#### How can this issue be replicated?

```
npm install -g astrum
astrum init ./public/pattern-library
astrum new buttons/default
```

And then open `astrum-demo/public/pattern-library/index.html` in Chrome browser.

#### Your environment

Platform: `MacOS`
OS Version: `High Sierra 10.13.2`
Node Version: `8.1.3`
NPM Version: `5.6.0`
Astrum Version: `1.9.5`

Chrome Version: `63.0.3239.132 (Official Build) (64-bit)`
Firefox Version: `57.0.4 (64-bit)`

**Comment by hankchizljaw** [comment]
Hey @nadalsol, thanks for reaching out! 

The Astrum front-end app is a single page Vue app. It is recommended that you run it in a web server environment though, to avoid issues like you mention.

Please see #140 where @NonPolynomial and @LukeMcGurdy made some great suggestions.

**Comment by nadalsol** [comment]
Hi @hankchizljaw , thanks for your answer.

I'm just pointing his out because I haven't found documentation about "How to run Astrum", so it has been confusing for me.

What about adding it to your [README.md file](https://github.com/NoDivide/astrum/blob/master/README.md)?

Congratulations for this great piece of work! 👏

**Comment by hankchizljaw** [comment]
Thanks @nadalsol!

I agree. I'll put an issue together to update the docs.
