### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by anandpatel** [NoDivide/astrum#16]
Is it possible to use RGBA values as well as HEX values in the colors array?

**Comment by RyanHavoc** [comment]
@anandpatel No presently but it wouldn't be too difficult to add the feature in. I've marked this issue as a feature request and added it to our roadmap.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;34Ki1GAs&#x2F;9-add-rgba-support-to-color-component-types"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add rgba support to color component types.</a>

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Vfr9YIHF&#x2F;17-extended-functionality-for-color-components"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Extended functionality for color components.</a>
