### ISSUE TITLE
FAQ: How compared to React StoryBook or UI Harness

### ISSUE THREAD

**Issue by TomFreudenberg** [NoDivide/astrum#17]
Hi, I am really impressed of your work and like to get a bit deeper in it. 

We are doing most of our jobs currently within meteor and react.

Therefor we are using React StoryBook (https://github.com/kadirahq/react-storybook) to build, test and describe our UI components. 

How would you differ to that tool? There are some more like StoryBook e.g. UI Harness (http://www.uiharness.com/start) or Chromatic (https://github.com/meteor/chromatic)

What do you think about them - what would be the benefit in using Astrum (even in addition) ?

Thanks for some feedback
Tom

**Comment by RyanHavoc** [comment]
@TomFreudenberg Good questions. I'm going to write a blog post about this, I'll post a link in the comments when it's up. Thanks.
