### ISSUE TITLE
Future of project with No Divide closure?

### ISSUE THREAD

**Issue by WolfieZero** [NoDivide/astrum#170]
With the news that [No Divide](https://ryanhavoc.com/blog/a-new-chapter) closing, I wondered what's the future of Astrum going forwards?

Aside from that, all the best to Dan, Ryan and Andy!

**Comment by RyanHavoc** [comment]
I’ll be continuing Astrum as a personal project. I’ll write a post about my plans for it in the new year. 😉

**Comment by DanCanetti** [comment]
> I’ll be continuing Astrum as a personal project. I’ll write a post about my plans for it in the new year. 😉

Great to hear and congrats to you and Dan on the new jobs!
