### ISSUE TITLE
Component is hidden when using absolution positioning

### ISSUE THREAD

**Issue by eirichmond** [NoDivide/astrum#171]
#### Tell us about the issue you are experiencing
in my patten library a component is showing a 'This component is hidden at this resolution.' panel instead of my component because my component has absolute positioning applied to it, if I disable absolute positioning it appears

#### What behaviour would you expect?
To show the component and its markup

#### How can this issue be replicated?
markup: <div class="entry-title"><span class="flash-tab tab--red">Coming Soon</span></div>
css:
.flash-tab {
    font-size: 13px;
    position: absolute;
    top: -10px;
    transform: rotate(15deg);
    padding: 6px 12px;
    right: 0px;
    opacity: .7;
    border-radius: 5px;
    color: #fff;
    &.tab--red {
    	background: #F44336;
    }
    &.tab--blue {
    	background: #2196F3;
    }
    &.tab--green {
    	background: #4CAF50;
    }
}

#### Screenshots / Screencast
<img width="1020" alt="screen shot 2018-12-01 at 10 59 10" src="https://user-images.githubusercontent.com/525490/49327398-0afc4700-f559-11e8-98b8-cd2ed550040c.png">
<img width="993" alt="screen shot 2018-12-01 at 11 06 09" src="https://user-images.githubusercontent.com/525490/49327408-22d3cb00-f559-11e8-91ea-ddbf2f73861a.png">

#### Your environment

Platform: Mac
OS Version: 10.13.6
Node Version: v9.4.0
NPM Version: 5.6.0
Astrum Version: 1.9.5

**Comment by RyanHavoc** [comment]
Hi. There’s a `disabled_auto_sample_hiding` option available for components. Search the `README.md` to find the details. That will allow you to override the behaviour you're seeing. Hope that helps.
