### ISSUE TITLE
Add your component markup message.

### ISSUE THREAD

**Issue by luvmex** [NoDivide/astrum#18]
#### Tell us about the issue you are experiencing

I add a color pattern use Command Line and deploy to server then page get this message.

"Add your component markup to /components/branding/color-palette/markup.html"

and then I add this  to data.json file.

   "group": "branding",
                    "name": "color-palette",
                    "title": "ccccccc",
                    "colors": [
                        "#4c4c4c",
                        "#7d8284",
                        "#a6b1b5",
                        "#e6eaf2",
                        "#FFFFFF"
                    ]

But It still show the markup message, I check the markup.html file it's empty. is there any about markup reference to add color or solve that message?

**Comment by RyanHavoc** [comment]
@luvmex I believe you've not added the `--type colors` option when creating the component. You can do this manually in your data.json file by adding a `type` key with the value of `colors` to the component like so:

    "group": "branding",
    "name": "color-palette",
    "title": "ccccccc",
    "type": "colors"
    "colors": [
        "#4c4c4c",
        "#7d8284",
        "#a6b1b5",
        "#e6eaf2",
        "#FFFFFF"
    ]

**Comment by luvmex** [comment]
I try the command line with "--type colors" but it didn't come up "data.json" file.
but I manually add the "type" and "colors" line, that can be use and show.

Thanks very much @RyanHavoc

**Comment by RyanHavoc** [comment]
That's strange. Are you on Windows or Mac?
