### ISSUE TITLE
Including components in other components

### ISSUE THREAD

**Issue by daspete** [NoDivide/astrum#19]
Is it possible to include a component in an other component? 

so for example:
you have an image component and would like to implement this in a slider component (looping through a json array with the datas for each image component)

**Comment by RyanHavoc** [comment]
@daspete Not presently. This would be an interesting challenge to find a solution to with the way Astrum currently works. I'll add this as a feature request for review.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7SoW2oRT&#x2F;10-component-embedding-within-other-components"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Component embedding within other components.</a>
