### ISSUE TITLE
Pattern library has already been initialized

### ISSUE THREAD

**Issue by ayoungh** [NoDivide/astrum#20]
#### Tell us about the issue you are experiencing

I am on windows 10, I can't seem to get init to work, should it work without a path if I am in the folder I want it to be installed in?

#### How can this issue be replicated?

![image](https://cloud.githubusercontent.com/assets/404328/16617741/50962406-437d-11e6-968b-889271ddda8a.png)

#### Screenshots / Screencast

![image](https://cloud.githubusercontent.com/assets/404328/16617721/39446362-437d-11e6-95b8-e4e7fec0b622.png)

This is all that has been created in the directory:

![image](https://cloud.githubusercontent.com/assets/404328/16617733/4586212e-437d-11e6-86c6-16898dd50600.png)

#### Your environment

Platform: Windows
OS Version: 10
Node Version: 6.0.0
NPM Version:3.8.6
Astrum Version: NPM installed this morning

**Comment by RyanHavoc** [comment]
Try deleting your `astrum-config.json` and from the folder you want to initialise into run:

`astrum init ./pattern-library`

Does that work?

**Comment by ayoungh** [comment]
Yes, Thanks (Does it need to have this path to do the init?)

**Comment by RyanHavoc** [comment]
@ayoungh You do need to specific somewhere to initialise Astrum into yes.
