### ISSUE TITLE
Browser Resize 

### ISSUE THREAD

**Issue by craigcoles** [NoDivide/astrum#21]
Top work folks! I do have one quick question...

Is there a reason as to why the loading screen is shown on resize? The only reason I ask is because it is hard to see how components behave on browser resize.

**Comment by RyanHavoc** [comment]
To be honest it's a bit of a legacy feature that we out in during Astrums first iteration. We're planning on removing it during an upcoming release.

**Comment by RyanHavoc** [comment]
I've added this to our development roadmap. [https://github.com/NoDivide/astrum/wiki/Project-Roadmap](https://github.com/NoDivide/astrum/wiki/Project-Roadmap)

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rhrK3C5f&#x2F;12-remove-resizing-mask-as-this-is-now-a-deprecated-feature-that-s-no-longer-needed"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Remove resizing mask as this is now a deprecated feature that&#39;s no longer needed.</a>

**Comment by RyanHavoc** [comment]
The realignment feature has now been removed as of version 1.6.3.
