### ISSUE TITLE
No way to check version of Astrum from the command line

### ISSUE THREAD

**Issue by ZakkMan** [NoDivide/astrum#22]
#### Tell us about the issue you are experiencing
Running `astrum -v` or `astrum --version` does not return the current version of astrum installed locally. 

#### What behaviour would you expect?
I would expect that these commands would list the current version of Astrum. 

#### How can this issue be replicated?
Run: `$ astrum -v` or `$ astrum --version`

#### Screenshots / Screencast

![screen shot 2016-07-08 at 4 17 28 pm](https://cloud.githubusercontent.com/assets/4991553/16700349/893590a2-4527-11e6-948f-7faef8793baf.png)

#### Your environment

Platform: Mac
OS Version: OS X Yosemite (10.10.5)
Node Version: v4.2.6
NPM Version: v3.5.3
Astrum Version: current version

**Comment by matt-west** [comment]
@ZakkMan I completely agree. Sorry that we missed this. I'll make sure it gets added in soon.

I've added this to our [roadmap document](https://github.com/NoDivide/astrum/wiki/Project-Roadmap).

**Comment by RyanHavoc** [comment]
@ZakkMan This is now available in Astrum 1.5.12!

`$ astrum -I`

Returns the Astrum instance you have installed.

`$ astrum -V`

Returns the version of Astrum you have installed via npm.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kKgBI1PQ&#x2F;1-add-ability-to-determine-astrum-version-from-command-line"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add ability to determine Astrum version from command line</a>
