### ISSUE TITLE
Sharing local build

### ISSUE THREAD

**Issue by craigcoles** [NoDivide/astrum#24]
#### Tell us about the issue you are experiencing

When I share my local build with someone (via IP address on the same network), it is looking for the files on there machine.

#### What behaviour would you expect?

For the person who I shared my local build with, to see my local build.

#### Your environment

Astrum Version: 1.5.12

**Comment by RyanHavoc** [comment]
@craigcoles I'm not sure how to test this here. How are you setup? Have you tried resolving the IP to a hostname?

Astrum makes Ajax calls to load in it's components so it must be getting confused somewhere along the way.

**Comment by craigcoles** [comment]
@RyanHavoc I am using python SimpleHTTPServer to serve the styleguide locally, so it is running on `localhost:8000`. If someone uses my IP and visits that address `http://192.168.XX.XXX:8000/` it throws an error trying to find the files

**Comment by danielfilho** [comment]
try using `http://xip.io/`. it works like a charm in my case :)
