### ISSUE TITLE
Attach a variable name to a color

### ISSUE THREAD

**Issue by NicolaSansom** [NoDivide/astrum#25]
Would it be possible to attach a variable name in addition to a hex code when creating a color within the color component type?

**Comment by RyanHavoc** [comment]
@NicolaSansom Not currently. I'll add this as a feature request.

**Comment by brendastorer** [comment]
+1 Came here to ask about this!

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;d7FSkwy8&#x2F;14-add-custom-text-to-color-variables"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add custom text to color variables.</a>

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Vfr9YIHF&#x2F;17-extended-functionality-for-color-components"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Extended functionality for color components.</a>

**Comment by AdrianoCahete** [comment]
Any update on this?

**Comment by JonasEriksson** [comment]
My vote for adding this as well, fine enough to manually add it into the colors section right now if possible (how?). It seems very clear that variable names, using SCSS etc., are very important to a styleguide/pattern-library, not just the finished hex value.
