### ISSUE TITLE
Javascript problem

### ISSUE THREAD

**Issue by bbyms** [NoDivide/astrum#29]
Hi, 

This is not really an issue, but a problem I'm having. I want to use JS files with my pattern library: material design lite, jquery and kendo and although I'm including them in the data.json file, it doesn't seem to be working.

This is my file:

"assets": {
        "css": [
          "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css",
          "https://fonts.googleapis.com/icon?family=Material+Icons",
          "../css/kendo.common-material.min.css",
          "../css/kendo.material.min.css",
          "../css/main.css"

        ],
        "js": [
          "../js/jquery.min.js",
          "../js/material.min.js",
          "../js/kendo.all.min.js",
          "../js/utils.js"
        ]
    }

Platform:
OS Version: OS X El Capitan

**Comment by RyanHavoc** [comment]
@bbyms Try removing the ../ from your paths. The paths aren't relative to your file system they're relative to the URL so in effect what Astrum is trying to resolve, for example, http://yourdomain.com/../js/jquery.min.js
