### ISSUE TITLE
Creating first group throwing js errors

### ISSUE THREAD

**Issue by mortocks** [NoDivide/astrum#30]
#### Tell us about the issue you are experiencing
errors with creating first group in brand new project

#### What behaviour would you expect?
creating new group without throwing errors

#### How can this issue be replicated?
(in public folder)
sudo npm install -g astrum
astrum init ./pattern-library
astrum new buttons/default

#### Screenshots / Screencast
![screenshot1468893186 2x](https://cloud.githubusercontent.com/assets/314196/16936080/6d552e64-4da7-11e6-804e-87165c596306.png)

#### Your environment

Platform: OSX
OS Version: 10.11.5
Node Version: v0.12.7
NPM Version: 3.8.3
Astrum Version: 1.5.12

**Comment by RyanHavoc** [comment]
@mortocks If you upgrade your version of NPM this error will go away.

**Comment by Oxicode** [comment]
me too

![image](https://cloud.githubusercontent.com/assets/1320709/17375992/24e978d2-5979-11e6-80c5-ddd678dddb8a.png)

OS: Ubuntu 14.04 trusty
Kernel: x86_64 Linux 4.2.0-c9
Node v0.10.35
Npm: 1.4.28
Astrum: 1.5.16

**Comment by matt-west** [comment]
@oxicode can you please try updating to the latest version of node.

**Comment by Oxicode** [comment]
Thx
