### ISSUE TITLE
TypeError in main.js

### ISSUE THREAD

**Issue by NicoMai** [NoDivide/astrum#34]
#### Tell us about the issue you are experiencing
TypeError in main.js -> undefined is not an object (evaluating 'this.content.pages.length') at isLoadingPage at line 468

#### How can this issue be replicated?
Initiate a new project with the actual version. I added a Color Scheme and an element for Buttons.

#### Screenshots / Screencast
[Konsole Safari](http://imgur.com/W8Gd6FB)

#### Your environment

Platform: macOS
OS Version: Sierra
Browser: Safari 10.0 (12602.1.40.4)
Node Version: 4.4.4
NPM Version: 3.10.3
Astrum Version: 1.5.15

**Comment by RyanHavoc** [comment]
@NicoMai Please could you paste the contents of your data.json file here?

**Comment by NicoMai** [comment]
`{
    "project_logo": null,
    "project_favicon": "favicon.png",
    "project_name": "deleted",
    "project_url": "deleted",
    "copyright_start_year": "2014",
    "client_name": "deleted",
    "client_url": "deleted",
    "creators": [
        {
            "name": "Nico",
            "url": null
        }
    ],
    "theme": {
        "border_color": "#E0E6ED",
        "highlight_color": "#F9FAFC",
        "brand_color": "#00585C",
        "background_color": "#FFFFFF",
        "code_highlight_theme": "github",
        "override_code_highlight_bg": "#F9FAFC",
        "sample_dark_background": "#333333",
        "show_project_name": true,
        "show_version": true,
        "max_width": null
    },
    "assets": {
        "css": [],
        "js": []
    },
    "font_libraries": {
        "typekit_code": null,
        "typography_web_fonts": null,
        "google_web_fonts": null
    },
    "content": {
        "show_first_page_on_load": true,
        "title": "Overview",
        "pages": [
            {
                "name": "introduction",
                "title": "Introduction",
                "file": "./pages/intro.md"
            }
        ]
    },
    "groups": [
        {
            "name": "branding",
            "title": "Branding",
            "components": [
                {
                    "group": "branding",
                    "name": "color-palette",
                    "title": "Color Palette",
                    "type": "colors",
                    "colors": ["#e2001a",
                    "#6f6f6f","#b2b2b2",
                  "#cccccc","f2f2f2",
                "#006ab3","fce0e2"]
                }
            ]
        },
        {
            "name": "buttons",
            "title": "Buttons",
            "components": [
                {
                    "group": "buttons",
                    "name": "primary",
                    "title": "Primary Button"
                }
            ]
        }
    ],
    "version": "1.5.10"
}
`

**Comment by RyanHavoc** [comment]
I've pasted your data.json into a fresh instance of Astrum and it's loaded first time...

I notice that you're actually on Astrum 1.5.10. Try running:

    $ astrum update

To get the latest version. Let me know how you get on.

**Comment by NicoMai** [comment]
I tried `astrum update` for three times and get the answer `Pattern library is up-to-date.`
Additional i tried `npm update -g astrum` without a message.

**Comment by RyanHavoc** [comment]
Astrum is at version 1.5.15. Could you run `npm -g list` and see what version you have install globally?

**Comment by NicoMai** [comment]
Sure ...
Here you can see the list:
/usr/local/lib
├─┬ astrum@1.5.10 -> /Users/nico/Documents/workspace/astrum/astrum
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├─┬ cwd@0.10.0
│ │ ├─┬ find-pkg@0.1.2
│ │ │ └─┬ find-file-up@0.1.2
│ │ │   └─┬ resolve-dir@0.1.0
│ │ │     └── expand-tilde@1.2.2
│ │ └── fs-exists-sync@0.1.0
│ ├─┬ fs-extra@0.28.0
│ │ ├── graceful-fs@4.1.4
│ │ ├── jsonfile@2.3.1
│ │ ├── klaw@1.3.0
│ │ ├── path-is-absolute@1.0.0
│ │ └─┬ rimraf@2.5.3
│ │   └─┬ glob@7.0.5
│ │     ├── fs.realpath@1.0.0
│ │     ├─┬ inflight@1.0.5
│ │     │ └── wrappy@1.0.2
│ │     ├── inherits@2.0.1
│ │     ├─┬ minimatch@3.0.2
│ │     │ └─┬ brace-expansion@1.1.5
│ │     │   ├── balanced-match@0.4.1
│ │     │   └── concat-map@0.0.1
│ │     └── once@1.3.3
│ ├─┬ global-modules@0.2.2
│ │ └─┬ global-prefix@0.1.4
│ │   ├── ini@1.3.4
│ │   ├─┬ osenv@0.1.3
│ │   │ ├── os-homedir@1.0.1
│ │   │ └── os-tmpdir@1.0.1
│ │   └─┬ which@1.2.10
│ │     └── isexe@1.1.2
│ ├─┬ inquirer@1.1.1
│ │ ├── ansi-escapes@1.4.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.1.0
│ │ ├─┬ external-editor@1.0.3
│ │ │ ├── extend@3.0.0
│ │ │ ├─┬ spawn-sync@1.0.15
│ │ │ │ ├─┬ concat-stream@1.5.1
│ │ │ │ │ ├─┬ readable-stream@2.0.6
│ │ │ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ │ │ ├── isarray@1.0.0
│ │ │ │ │ │ ├── process-nextick-args@1.0.7
│ │ │ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ │ │ └── util-deprecate@1.0.2
│ │ │ │ │ └── typedarray@0.0.6
│ │ │ │ └── os-shim@0.1.3
│ │ │ └─┬ temp@0.8.3
│ │ │   └── rimraf@2.2.8
│ │ ├─┬ figures@1.7.0
│ │ │ └── object-assign@4.1.0
│ │ ├── lodash@4.13.1
│ │ ├── mute-stream@0.0.6
│ │ ├─┬ pinkie-promise@2.0.1
│ │ │ └── pinkie@2.0.4
│ │ ├─┬ run-async@2.2.0
│ │ │ └── is-promise@2.1.0
│ │ ├── rx@4.1.0
│ │ ├─┬ string-width@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └── is-fullwidth-code-point@1.0.0
│ │ └── through@2.3.8
│ ├── is-windows@0.2.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── snyk@1.16.0 extraneous
├─┬ live-server@1.0.0
│ ├── colors@1.1.2 invalid
│ ├─┬ connect@3.4.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ finalhandler@0.4.1
│ │ │ ├── escape-html@1.0.3
│ │ │ ├─┬ on-finished@2.3.0
│ │ │ │ └── ee-first@1.1.1
│ │ │ └── unpipe@1.0.0
│ │ ├── parseurl@1.3.1
│ │ └── utils-merge@1.0.0
│ ├─┬ cors@2.7.1 invalid
│ │ └── vary@1.1.0 extraneous
│ ├─┬ event-stream@3.3.2 invalid
│ │ ├── duplexer@0.1.1 extraneous
│ │ ├── from@0.1.3 extraneous
│ │ ├── map-stream@0.1.0 extraneous
│ │ ├── pause-stream@0.0.11 extraneous
│ │ ├── split@0.3.3 extraneous
│ │ ├── stream-combiner@0.0.4 extraneous
│ │ └── through@2.3.8 extraneous
│ ├─┬ faye-websocket@0.10.0
│ │ └─┬ websocket-driver@0.6.5
│ │   └── websocket-extensions@0.1.1
│ ├─┬ http-auth@2.2.9
│ │ ├─┬ htpasswd@2.2.2
│ │ │ ├─┬ apache-crypt@1.1.0
│ │ │ │ └── unix-crypt-td-js@1.0.0
│ │ │ ├── apache-md5@1.0.4
│ │ │ ├── commander@2.0.0
│ │ │ └─┬ prompt@0.2.11
│ │ │   ├── pkginfo@0.4.0
│ │ │   ├─┬ read@1.0.7
│ │ │   │ └── mute-stream@0.0.6
│ │ │   ├── revalidator@0.1.8
│ │ │   ├─┬ utile@0.2.1
│ │ │   │ ├── async@0.2.10
│ │ │   │ ├── deep-equal@1.0.1
│ │ │   │ ├── i@0.3.5
│ │ │   │ ├─┬ mkdirp@0.5.1
│ │ │   │ │ └── minimist@0.0.8
│ │ │   │ ├── ncp@0.4.2
│ │ │   │ └─┬ rimraf@2.5.2
│ │ │   │   └─┬ glob@7.0.3
│ │ │   │     ├─┬ inflight@1.0.5
│ │ │   │     │ └── wrappy@1.0.2
│ │ │   │     ├── inherits@2.0.1
│ │ │   │     ├─┬ minimatch@3.0.0
│ │ │   │     │ └─┬ brace-expansion@1.1.4
│ │ │   │     │   ├── balanced-match@0.4.1
│ │ │   │     │   └── concat-map@0.0.1
│ │ │   │     ├─┬ once@1.3.3
│ │ │   │     │ └── wrappy@1.0.2
│ │ │   │     └── path-is-absolute@1.0.0
│ │ │   └─┬ winston@0.6.2
│ │ │     ├── async@0.1.22
│ │ │     ├── colors@0.6.2
│ │ │     ├── cycle@1.0.3
│ │ │     ├── eyes@0.1.8
│ │ │     ├── pkginfo@0.2.3
│ │ │     ├── request@2.9.203
│ │ │     └── stack-trace@0.0.9
│ │ └── node-uuid@1.4.1
│ ├─┬ morgan@1.7.0
│ │ ├── basic-auth@1.0.4
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── depd@1.1.0
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ └── on-headers@1.0.1
│ ├── UNMET DEPENDENCY object-assign@latest
│ ├─┬ opn@4.0.2 invalid
│ │ ├── object-assign@4.1.0 extraneous
│ │ └── pinkie-promise@2.0.1 extraneous
│ ├─┬ send@0.13.2 invalid
│ │ ├── debug@2.2.0 extraneous
│ │ ├── depd@1.1.0 extraneous
│ │ ├── destroy@1.0.4 extraneous
│ │ ├── escape-html@1.0.3 extraneous
│ │ ├── etag@1.7.0 extraneous
│ │ ├── fresh@0.3.0 extraneous
│ │ ├── http-errors@1.3.1 extraneous
│ │ ├── mime@1.3.4 extraneous
│ │ ├── ms@0.7.1 extraneous
│ │ ├── on-finished@2.3.0 extraneous
│ │ ├── range-parser@1.0.3 extraneous
│ │ └── statuses@1.2.1 extraneous
│ ├─┬ serve-index@1.7.3
│ │ ├─┬ accepts@1.2.13
│ │ │ └── negotiator@0.5.3
│ │ ├── batch@0.5.3
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── escape-html@1.0.3
│ │ ├─┬ http-errors@1.3.1
│ │ │ ├── inherits@2.0.1
│ │ │ └── statuses@1.3.0
│ │ ├─┬ mime-types@2.1.11
│ │ │ └── mime-db@1.23.0
│ │ └── parseurl@1.3.1
│ └─┬ watchr@2.3.10
│   └─┬ bal-util@1.18.0
│     ├── ambi@2.0.0
│     ├── eachr@2.0.4
│     ├── extendr@2.0.1
│     ├── getsetdeep@2.0.0
│     ├── safecallback@1.0.1
│     ├── safefs@2.0.3
│     ├── taskgroup@2.0.0
│     └── typechecker@2.0.8
├─┬ npm@3.10.3
│ ├── abbrev@1.0.9
│ ├── ansi-regex@2.0.0
│ ├── ansicolors@0.3.2
│ ├── ansistyles@0.1.3
│ ├── aproba@1.0.4
│ ├── archy@1.0.0
│ ├── asap@2.0.4
│ ├── chownr@1.0.1
│ ├── cmd-shim@2.0.2
│ ├─┬ columnify@1.5.4
│ │ └─┬ wcwidth@1.0.0
│ │   └─┬ defaults@1.0.3
│ │     └── clone@1.0.2
│ ├─┬ config-chain@1.1.10
│ │ └── proto-list@1.2.4
│ ├── debuglog@1.0.1
│ ├── dezalgo@1.0.3
│ ├── editor@1.0.0
│ ├── fs-vacuum@1.2.9
│ ├── fs-write-stream-atomic@1.0.8
│ ├── fstream@1.0.10
│ ├─┬ fstream-npm@1.1.0
│ │ └─┬ fstream-ignore@1.0.5
│ │   └─┬ minimatch@3.0.0
│ │     └─┬ brace-expansion@1.1.4
│ │       ├── balanced-match@0.4.1
│ │       └── concat-map@0.0.1
│ ├─┬ glob@7.0.4
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.5
│ │ │   ├── balanced-match@0.4.1
│ │ │   └── concat-map@0.0.1
│ │ └── path-is-absolute@1.0.0
│ ├── graceful-fs@4.1.4
│ ├── has-unicode@2.0.1
│ ├── hosted-git-info@2.1.5
│ ├── iferr@0.1.5
│ ├── imurmurhash@0.1.4
│ ├── inflight@1.0.5
│ ├── inherits@2.0.1
│ ├── ini@1.3.4
│ ├─┬ init-package-json@1.9.4
│ │ ├─┬ glob@6.0.4
│ │ │ ├─┬ minimatch@3.0.0
│ │ │ │ └─┬ brace-expansion@1.1.4
│ │ │ │   ├── balanced-match@0.4.1
│ │ │ │   └── concat-map@0.0.1
│ │ │ └── path-is-absolute@1.0.0
│ │ └── promzard@0.3.0
│ ├── lockfile@1.0.1
│ ├── lodash._baseindexof@3.1.0
│ ├─┬ lodash._baseuniq@4.6.0
│ │ ├── lodash._createset@4.0.3
│ │ └── lodash._root@3.0.1
│ ├── lodash._bindcallback@3.0.1
│ ├── lodash._cacheindexof@3.0.2
│ ├── lodash._createcache@3.1.2
│ ├── lodash._getnative@3.9.1
│ ├─┬ lodash.clonedeep@4.3.2
│ │ └── lodash._baseclone@4.5.3
│ ├── lodash.restparam@3.6.1
│ ├─┬ lodash.union@4.4.0
│ │ ├── lodash._baseflatten@4.2.1
│ │ └── lodash.rest@4.0.3
│ ├── lodash.uniq@4.3.0
│ ├─┬ lodash.without@4.2.0
│ │ ├─┬ lodash._basedifference@4.5.0
│ │ │ └── lodash._root@3.0.1
│ │ └── lodash.rest@4.0.3
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ node-gyp@3.3.1
│ │ ├─┬ glob@4.5.3
│ │ │ └─┬ minimatch@2.0.10
│ │ │   └─┬ brace-expansion@1.1.3
│ │ │     ├── balanced-match@0.3.0
│ │ │     └── concat-map@0.0.1
│ │ ├─┬ minimatch@1.0.0
│ │ │ ├── lru-cache@2.7.3
│ │ │ └── sigmund@1.0.1
│ │ ├─┬ npmlog@2.0.4
│ │ │ ├── ansi@0.3.1
│ │ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ │ └── delegates@1.0.0
│ │ │ └─┬ gauge@1.2.7
│ │ │   ├─┬ lodash.pad@4.4.0
│ │ │   │ ├── lodash._baseslice@4.0.0
│ │ │   │ ├── lodash._basetostring@4.12.0
│ │ │   │ └── lodash.tostring@4.1.3
│ │ │   ├─┬ lodash.padend@4.5.0
│ │ │   │ ├── lodash._baseslice@4.0.0
│ │ │   │ ├── lodash._basetostring@4.12.0
│ │ │   │ └── lodash.tostring@4.1.3
│ │ │   └─┬ lodash.padstart@4.5.0
│ │ │     ├── lodash._baseslice@4.0.0
│ │ │     ├── lodash._basetostring@4.12.0
│ │ │     └── lodash.tostring@4.1.3
│ │ └─┬ path-array@1.0.1
│ │   └─┬ array-index@1.0.0
│ │     ├─┬ debug@2.2.0
│ │     │ └── ms@0.7.1
│ │     └─┬ es6-symbol@3.0.2
│ │       ├── d@0.1.1
│ │       └─┬ es5-ext@0.10.11
│ │         └── es6-iterator@2.0.0
│ ├── nopt@3.0.6
│ ├── normalize-git-url@3.0.2
│ ├─┬ normalize-package-data@2.3.5
│ │ └─┬ is-builtin-module@1.0.0
│ │   └── builtin-modules@1.1.1
│ ├── npm-cache-filename@1.0.2
│ ├── npm-install-checks@3.0.0
│ ├── npm-package-arg@4.2.0
│ ├─┬ npm-registry-client@7.1.2
│ │ ├─┬ concat-stream@1.5.1
│ │ │ ├─┬ readable-stream@2.0.6
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── isarray@1.0.0
│ │ │ │ ├── process-nextick-args@1.0.7
│ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ └── util-deprecate@1.0.2
│ │ │ └── typedarray@0.0.6
│ │ └── retry@0.8.0
│ ├── npm-user-validate@0.1.4
│ ├─┬ npmlog@3.1.2
│ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.6.0
│ │ │ ├── has-color@0.1.7
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── signal-exit@3.0.0
│ │ │ ├─┬ string-width@1.0.1
│ │ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.0
│ │ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │ │   └── number-is-nan@1.0.0
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ ├── once@1.3.3
│ ├── opener@1.4.1
│ ├─┬ osenv@0.1.3
│ │ ├── os-homedir@1.0.1
│ │ └── os-tmpdir@1.0.1
│ ├── path-is-inside@1.0.1
│ ├─┬ read@1.0.7
│ │ └── mute-stream@0.0.5
│ ├── read-cmd-shim@1.0.1
│ ├─┬ read-installed@4.0.3
│ │ └── util-extend@1.0.3
│ ├─┬ read-package-json@2.0.4
│ │ ├─┬ glob@6.0.4
│ │ │ ├─┬ minimatch@3.0.0
│ │ │ │ └─┬ brace-expansion@1.1.3
│ │ │ │   ├── balanced-match@0.3.0
│ │ │ │   └── concat-map@0.0.1
│ │ │ └── path-is-absolute@1.0.0
│ │ └─┬ json-parse-helpfulerror@1.0.3
│ │   └── jju@1.3.0
│ ├── read-package-tree@5.1.5
│ ├─┬ readable-stream@2.1.4
│ │ ├── buffer-shims@1.0.0
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@1.0.0
│ │ ├── process-nextick-args@1.0.7
│ │ ├── string_decoder@0.10.31
│ │ └── util-deprecate@1.0.2
│ ├── readdir-scoped-modules@1.0.2
│ ├── realize-package-specifier@3.0.3
│ ├─┬ request@2.72.0
│ │ ├── aws-sign2@0.6.0
│ │ ├─┬ aws4@1.3.2
│ │ │ └─┬ lru-cache@4.0.1
│ │ │   ├── pseudomap@1.0.2
│ │ │   └── yallist@2.0.0
│ │ ├─┬ bl@1.1.2
│ │ │ └─┬ readable-stream@2.0.6
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── isarray@1.0.0
│ │ │   ├── process-nextick-args@1.0.6
│ │ │   ├── string_decoder@0.10.31
│ │ │   └── util-deprecate@1.0.2
│ │ ├── caseless@0.11.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.0
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@1.0.0-rc4
│ │ │ └── async@1.5.2
│ │ ├─┬ har-validator@2.0.6
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ └── supports-color@2.0.0
│ │ │ ├─┬ commander@2.9.0
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ is-my-json-valid@2.13.1
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@2.0.0
│ │ │ │ └── xtend@4.0.1
│ │ │ └─┬ pinkie-promise@2.0.1
│ │ │   └── pinkie@2.0.4
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.2.2
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── json-schema@0.2.2
│ │ │ │ └── verror@1.3.6
│ │ │ └─┬ sshpk@1.7.4
│ │ │   ├── asn1@0.2.3
│ │ │   ├─┬ dashdash@1.13.0
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├── jodid25519@1.0.2
│ │ │   ├── jsbn@0.1.0
│ │ │   └── tweetnacl@0.14.3
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.10
│ │ │ └── mime-db@1.22.0
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.8.1
│ │ ├── qs@6.1.0
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.2.2
│ │ └── tunnel-agent@0.4.2
│ ├── retry@0.9.0
│ ├── rimraf@2.5.2
│ ├── semver@5.1.0
│ ├── sha@2.0.1
│ ├── slide@1.1.6
│ ├── sorted-object@2.0.0
│ ├── strip-ansi@3.0.1
│ ├─┬ tar@2.2.1
│ │ └── block-stream@0.0.8
│ ├── text-table@0.2.0
│ ├── uid-number@0.0.6
│ ├── umask@1.1.0
│ ├─┬ unique-filename@1.1.0
│ │ └── unique-slug@2.0.0
│ ├── unpipe@1.0.0
│ ├─┬ validate-npm-package-license@3.0.1
│ │ ├─┬ spdx-correct@1.0.2
│ │ │ └── spdx-license-ids@1.2.0
│ │ └─┬ spdx-expression-parse@1.0.2
│ │   ├── spdx-exceptions@1.0.4
│ │   └── spdx-license-ids@1.2.0
│ ├─┬ validate-npm-package-name@2.2.2
│ │ └── builtins@0.0.7
│ ├─┬ which@1.2.10
│ │ └── isexe@1.1.2
│ ├── wrappy@1.0.2
│ └── write-file-atomic@1.1.4
└── typescript@1.8.10


And i get an Error:
[Terminal Error after npm -g list](http://imgur.com/Z3CVwQa)

**Comment by RyanHavoc** [comment]
I see the problem. I'll write a fix, but you'll need to update your global Astrum once it's resolved. Looks like your using a form of Astrum locally?

**Comment by NicoMai** [comment]
I have the local fork there and a second directory with the working instance of astrum.

**Comment by NicoMai** [comment]
i'll try

**Comment by RyanHavoc** [comment]
It should be:

```
cd /Users/nico/Documents/workspace/astrum/astrum
git remote add upstream http://github.com/NoDivide/astrum.git
git pull upstream master
```

**Comment by NicoMai** [comment]
It should, but wasn't. After a short terminal session it works fine. But only with FireFox on macOS. In new Safari 10 i can only see the message "Building pattern library...".
