### ISSUE TITLE
Extend color content type for color descriptions

### ISSUE THREAD

**Issue by bitstarr** [NoDivide/astrum#35]
To streamline communication designers define clear names for colours, so everybody is talking about the same. Also these names may be used as CSS variables.

Take the following LESS code for example:
```less
@red: #d51130;
@grey-sky: #f3f3f3;
@grey-steel: #bac2c4;
@grey-dark: #6c7475;

@border-color: @grey-steel;
@brand-color: @red;
@brand-color-alt: darken(@red, 50%);
```

Please provide a way to add those information to a colour in the content type. I would wish to define the following information for a colour:
* colour
* complimentary/shade colour
* name
* variable name

Additional aliases could be described in an extra group to make the difference clear.

Sorry, i'm not able (or too blind) to add a label to this issue :(

**Comment by RyanHavoc** [comment]
@bitstarr I've added this to our development roadmap and marked it as a feature request. [https://github.com/NoDivide/astrum/wiki/Project-Roadmap](https://github.com/NoDivide/astrum/wiki/Project-Roadmap)

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Vfr9YIHF&#x2F;17-extended-functionality-for-color-components"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Extended functionality for color components.</a>
