### ISSUE TITLE
Not loading external images

### ISSUE THREAD

**Issue by bitstarr** [NoDivide/astrum#37]
#### Tell us about the issue you are experiencing
I added an image to my markup which is not hosted on the same domain and it doesn't load.

#### What behaviour would you expect?
Images should be loaded without a restriction of host/cross domain.

#### How can this issue be replicated?
I used this example:
```html
<img src="//unsplash.it/300/300/?random" class="employee-img" alt="Frank" width="300" height="300" />
```

#### Your environment

Platform: Debian/Apache
Node Version: 5.10.1
NPM Version:  3.8.3
Astrum Version: 1.5.15

**Comment by RyanHavoc** [comment]
@bitstarr Just for arguments sake, try adding a protocol to the src, e.g. http.

**Comment by bitstarr** [comment]
@RyanHavoc I tried but it hasn't changed.

**Comment by RyanHavoc** [comment]
@bitstarr That's strange. I don't understand how this could be an Astrum issue. We use images that aren't hosted on the same domain all the time, our demo for example renders images from imgix: [http://astrum.nodividestudio.com/pattern-library/#group-tabs-component-tab-panes](http://astrum.nodividestudio.com/pattern-library/#group-tabs-component-tab-panes)

**Comment by bitstarr** [comment]
@RyanHavoc You are right. Seems that some dummy image providers are not working. I switched to placeimg.com which works. Maybe it's because of the server configuration. But i can't say what's the exact reason for this behaviour.

Sorry for the disruption :(
