### ISSUE TITLE
Changes to /pages/intro.md don't register

### ISSUE THREAD

**Issue by zachfedor** [NoDivide/astrum#39]
#### Tell us about the issue you are experiencing
I have edited `/pages/intro.md` to replace the default content with a simple paragraph. However, the original content is still showing. Grepping every file in the project for the original content comes up empty, so it must be a cacheing issue. I've refreshed the page in Chrome, hard refreshed it, and even restarted the [http-server](https://www.npmjs.com/package/http-server). I opened the page in Incognito Mode and I can see my changes, but it still hasn't updated in my regular browser.

#### What behaviour would you expect?
On save, changes to a page should be reflected on the served project on a refresh of the page, or at least on killing the server and restarting it.

#### Your environment

Platform: OS X
OS Version: 10.11.4
Node Version: 5.3.0
NPM Version: 3.5.2
Astrum Version: 1.5.16

**Comment by RyanHavoc** [comment]
@zachfedor This has been fixed in the latest release.

**Comment by mofodox** [comment]
@RyanHavoc Experiencing the bug on the latest version. Here's the issue ticket: [#43](https://github.com/NoDivide/astrum/issues/43) :(
