### ISSUE TITLE
How to add multiple custom stylesheet & javascript files using data.json?

### ISSUE THREAD

**Issue by mofodox** [NoDivide/astrum#42]
#### Tell us about the issue you are experiencing

Currently, I'm experiencing an issue where I can't get my custom stylesheet and javascript files to work. Maybe it's me I guess. This doesn't have any issue with Bootstrap though. Does it really possible to use multiple stylesheet and javascript files?

#### What behaviour would you expect?

I just want to get my custom stylesheet & javascript files to work. Apart from that I'm currently loving Astrum.

#### How can this issue be replicated?

Nil

#### Screenshots / Screencast

Nil

#### Your environment

Platform: Mac OS X
OS Version: OS X El Capitan
Node Version: 6.2.2
NPM Version: 3.9.5
Astrum Version: 1.5.16

**Comment by MichalSvatos** [comment]
This doesn't work for you?
```
    "assets": {
        "css": [
            "/css/styles.css",
            "/css/other-styles.css"
        ],
        "js": [
            "/js/jquery.min.js",
            "/js/script.js",
            "/js/other-script.js"
        ]
    },
```

**Comment by RyanHavoc** [comment]
@mofodox Could you share your `data.json` file?

**Comment by mofodox** [comment]
@RyanHavoc @MichalSvatos Here's the assets object from the [data.json file](https://cl.ly/1I3v3k2s3K3l)

**Comment by RyanHavoc** [comment]
@mofodox That should work... try running your data.json file through a validator: [http://jsonlint.com/](http://jsonlint.com/)

Do you get any errors?

**Comment by mofodox** [comment]
@RyanHavoc The json file is valid. No errors 👍

**Comment by mofodox** [comment]
@RyanHavoc All's good the files are loaded. Thank you! :)
