### ISSUE TITLE
Stuck at 'Building pattern library...' screen

### ISSUE THREAD

**Issue by mofodox** [NoDivide/astrum#43]
#### Tell us about the issue you are experiencing

The pattern library is not loading... I'm stuck at 'Building pattern library' screen.

#### What behaviour would you expect?

It supposed to load the pattern library and suddenly I'm experiencing. I noticed after I edited the ```intro.md``` file. Before it works smoothly. 

#### How can this issue be replicated?

Nil

#### Screenshots / Screencast

Here's a [screencast](https://cl.ly/2N3B3i1M1R1C) on it.

#### Your environment

Platform: Mac
OS Version: OS X El Capitan
Node Version: 6.2.2
NPM Version: 3.9.5
Astrum Version: 1.5.16

**Comment by RyanHavoc** [comment]
@MichalSvatos Open up your Web Inspector. Are you getting any errors on the console? Can you send me a screenshot?

**Comment by RyanHavoc** [comment]
@mofodox I've just tested the latest version 1.5.17 with a fresh instance and it builds correctly. Have you updated Astrum:

`npm update -g astrum`

Then updated your instance (from the root folder):

`astrum update`

**Comment by mofodox** [comment]
@RyanHavoc Here's the [screenshot](https://cl.ly/3L1D2J1k043a). I received 2 errors.

I'm about to update astrum. I'll let you know if it's fixed.

**Comment by RyanHavoc** [comment]
@mofodox Validate your json file to ensure there are no errors and if it's still occurring paste your `data.json` file here for us to have a look.

**Comment by yisraelgrimes** [comment]
I seem to be having the same problem. The difference is that mine has been stuck at the building screen since I installed it. Should I start another thread?

**Comment by mofodox** [comment]
@RyanHavoc Noted!

**Comment by mofodox** [comment]
@yisraelgrimes Do you have a local server setup? Because that's what I've experienced before. If you don't install MAMP or XAMPP and when you ```astrum init [path_to_htdocs]```, it will start running the pattern library.

**Comment by yisraelgrimes** [comment]
I do, but this project is a kind of a static html testing environment so isn't running through the server. I'll move it over and see if that fixes it.

**Comment by yisraelgrimes** [comment]
Huzzah! Thanks for the help!

**Comment by mofodox** [comment]
@yisraelgrimes No worries! Glad to help ;)

**Comment by mofodox** [comment]
@RyanHavoc Oh it's all working now ;)

I'll close the thread. Thank you! 😊
