### ISSUE TITLE
jQuery not loading

### ISSUE THREAD

**Issue by mofodox** [NoDivide/astrum#44]
#### Tell us about the issue you are experiencing

jQuery not load for the pattern library. I received the error on the web console. I've included the jQuery library on the ```data.json```

#### What behaviour would you expect?

It should be loaded via ```data.json```

#### How can this issue be replicated?

Nil

#### Screenshots / Screencast

Here are a couple of screenshots on the error and my ```data.json``` file:

[Web console error](https://cl.ly/2F0y2u2S0j46)
[data.json file](https://cl.ly/1f3E2x2K1U0G)

**Updated**

I did a check whether jQuery is loaded and I received this: [3](https://cl.ly/1X2m1t221a01) but the pattern library doesn't get the jQuery. 

#### Your environment

Platform: Mac
OS Version: OS X El-Capitan
Node Version: 6.2.2
NPM Version: 3.9.5
Astrum Version: 1.5.17

**Comment by matt-west** [comment]
Hi @mofodox,

The JavaScript assets specified in the `data.json` are loaded asynchronously after the initial page load. I'm pretty sure that your other JS files are loading before jQuery and that's why you're getting the error. Unfortunately we don't currently have a solution for this through the `data.json` file.

As a workaround, please edit the `index.html` file and include jQuery before the `<ndpl-script>` element in the `<head>`.

**Comment by matt-west** [comment]
@mofodox Just checking in to see if you managed to resolve this?

**Comment by mofodox** [comment]
@matt-west Oops almost forgot to give you the update! I tried the solution you gave. And it's working ;)

Thank you!

**Comment by matt-west** [comment]
@mofodox Awesome :)

**Comment by revrng** [comment]
Hey, 

thanks for your awesome library!

I stumbled about the same error as described above. Your workaround worked for me. 

What do you think about extending the `data.json` to something like:

```
"assets": {
    "css": [],
    "vendor_js": [],
    "main_js": []
}
```

Inside the index.hml it would be possible to add something like:

```
    <ndpl-script v-for="script in assets.vendor_js"
                 :script="script"
                 inline-template>
        <script :src="script"></script>
    </ndpl-script>

    <ndpl-script v-for="script in assets.main_js"
                 :script="script"
                 v-if="loaded"
                 inline-template>
        <script :src="script"></script>
    </ndpl-script>
```

All JavaScript files inside of assets.vendor_js are then loaded before the JavaScript of main_js. 

I would like to contribute a PR if you want.

René

**Comment by RyanHavoc** [comment]
@revrng We inject javascript in a different way in version 2 you can pull the `release/2.0.0` branch to test with. :-)
