### ISSUE TITLE
Component type - markup typo

### ISSUE THREAD

**Issue by Nibblesh** [NoDivide/astrum#45]
#### Tell us about the issue you are experiencing

the markdown has two different types of dashes which won't be parseable by a console for the script in the following section:
https://github.com/NoDivide/astrum#component-types

astrum new branding/color-palette —-type colors

**Comment by matt-west** [comment]
Hi @Nibblesh,

We were having some issues were GitHub was converting `--` to `–` which was messing with the code samples and so we changed to using two different dashes. It looks like they've resolved this issue now so I've updated the docs.
