### ISSUE TITLE
Hide portions of code samples 

### ISSUE THREAD

**Issue by henwen** [NoDivide/astrum#46]
Displaying a component in its full glory often requires a good amount of placeholder content (lorem ipsum,  placehold.it images, fixed-height divs to diagram layouts). This placeholder content can clutter up the code sample, making it less readable for users. 

It'd be great to optionally hide portions of code from the sample. This could be as simple as wrapping it in a comment flag. 

Code in `markup.html`:

```
<div class="component">
  <div class="component__body">
    <!-- your content here -->

    <!-- astrum-hidden-start -->
      <p>Health goth irony ramps keffiyeh. Fingerstache tacos deep v yr readymade, skateboard tattooed listicle hammock sriracha blue bottle humblebrag cliche. Meh gochujang scenester, kitsch selvage franzen keytar master cleanse small batch four dollar toast cred fingerstache gluten-free ethical. Flexitarian mumblecore tofu, synth gentrify slow-carb whatever iPhone pug tousled. Normcore meh YOLO iPhone, deep v pickled wayfarers beard keffiyeh PBR&B venmo freegan mixtape DIY. Readymade photo booth tilde, tote bag heirloom tacos normcore cold-pressed gentrify man braid four dollar toast try-hard sriracha. Thundercats paleo shoreditch synth.</p>
      <img src="image.com">
      <button>Click Here</button>
    <!-- astrum-hidden-end -->
  </div>
</div>
```

Code sample in UI:

```
<div class="component">
  <div class="component__body">
    <!-- your content here -->
  </div>
</div>
```

Loving Astrum so far! Keep up the good work!

PS - apologies for not adding the `Feature Request` label, think it's a permissions thing.

**Comment by matt-west** [comment]
Good proposal @henwen. I agree that having this functionality would be valuable.

We're currently exploring the possibility of adding a really simple templating language to make it easier to re-use component markup within other components in Astrum. I think it would be a natural fit to add this into the mix at the same time.

I've added this request to our roadmap document.
https://github.com/NoDivide/astrum/wiki/Project-Roadmap

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7SoW2oRT&#x2F;10-add-templating-functionality-for-increased-reusability"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add templating functionality for increased reusability.</a>
