### ISSUE TITLE
Set max-width for markdown text

### ISSUE THREAD

**Issue by henwen** [NoDivide/astrum#47]
Just a simple UX/readability issue here – 

Without a `max-width` for rendered markdown on `Pages` and full-width `Components`, each line of text runs very long on medium/large screens (150+ characters per line vs the [recommended](http://baymard.com/blog/line-length-readability) 50-75 characters).

**Comment by matt-west** [comment]
Thanks for the suggestion @henwen. I completely agree. I'll make sure this gets in the next release.

**Comment by henwen** [comment]
Excellent. Thanks for the quick response.
