### ISSUE TITLE
Astrum does not work when offline

### ISSUE THREAD

**Issue by raffomania** [NoDivide/astrum#48]
#### Tell us about the issue you are experiencing

When disconnecting from the internet, Astrum stops working because all the assets are loaded from CDNs.
#### What behaviour would you expect?

When offline, Astrum works as usual.
#### How can this issue be replicated?

Disconnect from the internet and load the application.
#### Screenshots / Screencast

http://i.imgur.com/CJZXz7L.png
#### Your environment

Platform: Arch Linux
OS Version: All packages up to date
Node Version: 6.3.1
NPM Version: 3.10.5
Astrum Version: 1.5.17

**Comment by matt-west** [comment]
Hi @raffomania, I've added this to our roadmap. 
https://github.com/NoDivide/astrum/wiki/Project-Roadmap

**Comment by raffomania** [comment]
I could prepare a PR if you want. What do you think of a small function in `manager/utils.js` that downloads the correct versions when running `astrum new` or `astrum update`?

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ry8YRTkf&#x2F;19-package-js-dependencies-with-astrum-so-that-it-works-offline-out-of-the-box"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Package JS dependencies with Astrum so that it works offline out of the box.</a>

**Comment by RyanHavoc** [comment]
@raffomania The new version of Astrum (2.0.0) address this issue and now works offline. It's currently in pre-release and you can have a play with it now. Details here: https://github.com/NoDivide/astrum/releases/tag/2.0.0-rc.0

**Comment by raffomania** [comment]
Awesome work, thanks!

**Comment by Madhu2911** [comment]
How to run an astrum file after creating the components?

**Comment by RyanHavoc** [comment]
@Madhu2911 Could you clarify what you mean by your question please?

**Comment by Madhu2911** [comment]
using npm how to run astrum??
is this need any API to run?

**Comment by RyanHavoc** [comment]
@Madhu2911 No, just install Astrum globally:

`npm install -g astrum`

And initialise an instance in your web project:

`astrum init ./pattern-library`

Usage instructions are here: https://github.com/NoDivide/astrum

**Comment by Madhu2911** [comment]
When I try to run I am getting error like this
npm ERR! missing script: start

**Comment by RyanHavoc** [comment]
@Madhu2911 Do you want to open a new issue for this (as it's not related to this one) and provide the complete output?

**Comment by Madhu2911** [comment]
yeah

**Comment by Madhu2911** [comment]
Is it possible in astrum to create all the required components in a single step? Because creating every single component take much time. It becomes a time consuming one...
