### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by dlewand691** [NoDivide/astrum#50]
What is the recommended best practice to use a custom set of fonts other than Typekit, etc.?

**Comment by RyanHavoc** [comment]
@dlewand691 Are you referring to using @font-face instead of a service?

**Comment by dlewand691** [comment]
Yep. I know you can just use your own CSS file which is fine, but is there a cleaner way other than that?

**Comment by RyanHavoc** [comment]
If you want to include a web service other than Typekit we've added two helpers, one for Google Fonts and one for Typgraphy.com. Just paste the styles sheet they provide you in there. If you're using something other than those two services (and it's just a stylesheet that the service provides you) you can just add it to assets => css array.

If you're using a service that provides JS (like TypeKit does) we'll have to do some testing to find the cleanest way to include it.

If you're just using @font-face then just include this in your stylesheet.

With out more information about your setup I'm not sure how to advise you further?

**Comment by dlewand691** [comment]
That's plenty, thank you for the clarification!
