### ISSUE TITLE
"Realigning Pattern Library" gets really annoying

### ISSUE THREAD

**Issue by raffomania** [NoDivide/astrum#52]
#### Tell us about the issue you are experiencing
When developing responsive components, I'm resizing the browser window a lot. Waiting for 1-2 seconds for the message "Realigning pattern library" to go away gets annoying.

#### What behaviour would you expect?
No message or other transition. Modern CSS allows a page to be responsive without rebuilding the page.

#### How can this issue be replicated?
Open a pattern library and resize the browser window.

#### Your environment

Platform: Arch Linux
OS Version: all packages up to date
Node Version: 6.3.1
NPM Version: 3.10.5
Astrum Version: 1.5.17

**Comment by RyanHavoc** [comment]
@raffomania This is on our development roadmap. This is a legacy feature we'll be removing in the next release.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rhrK3C5f&#x2F;12-remove-resizing-mask-as-this-is-now-a-deprecated-feature-that-s-no-longer-needed"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Remove resizing mask as this is now a deprecated feature that&#39;s no longer needed.</a>

**Comment by RyanHavoc** [comment]
The realignment feature has now been removed as of version 1.6.3.

**Comment by raffomania** [comment]
Thanks a lot!
