### ISSUE TITLE
Overriding base styles.css and themes, please include master .scss file

### ISSUE THREAD

**Issue by dlewand691** [NoDivide/astrum#55]
Would be great to have a default sass file included to override the base `styles.css` file and also control how it's minified, its output name and output directory. Without adding my own CSS I've had to un-minify and then manually edit elements in the minified CSS. 

Some elements of the theme don't get applied properly as well. For example, I was expecting the classes `ndpl-component__sample-missing ndpl-info` to use my theme color but it didn't. Font family should also be able to be controlled via the theme. Opacity of the colors would be great too for things like the `highlight_color` instead of HEX value.

Overall, much finer control of the master theme styles would be a huge help.

**Comment by RyanHavoc** [comment]
All you have to do is include a stylesheet in assets => css to override Astrum's styles. You may have to use !important in some cases.

**Comment by dlewand691** [comment]
That's true but it requires a lot of rework to find the elements that need to change. If you had a master sass file with all the variables available to change, you could theme quicker and easier. You can move all font sizes, paddings, colors, borders, etc out of the CSS and into variables similar to how Zurb's Foundation framework works. Much easier and more robust than having to hunt and peck for what to change.

[http://foundation.zurb.com/sites/docs/global.html](http://foundation.zurb.com/sites/docs/global.html)
