### ISSUE TITLE
Customize "Pattern Library" subtitle in side bar

### ISSUE THREAD

**Issue by dlewand691** [NoDivide/astrum#56]
The subtitle "Pattern Library" would be nice to be flexible in case you don't want to use that description or leave off entirely.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0R340N7F&#x2F;24-facility-to-control-titles-on-sidebar"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Facility to control titles on sidebar.</a>

**Comment by Oxicode** [comment]
+1

**Comment by RyanHavoc** [comment]
This feature has just been release in the latest version: [Release Notes](https://github.com/NoDivide/astrum/releases/tag/1.7.0)

Enjoy!
