### ISSUE TITLE
No dark preview background if code sample is disabled

### ISSUE THREAD

**Issue by EOGreer** [NoDivide/astrum#58]
When adding a new component that requires a dark background for the preview, if you disable the code sample Astrum does not add `"sample_dark_background": true` into the data.json

<img width="355" alt="screen shot 2016-08-16 at 11 24 59" src="https://cloud.githubusercontent.com/assets/4273115/17696084/1736b4ae-63a4-11e6-9bd0-05cccd345de2.png">
results in
<img width="232" alt="screen shot 2016-08-16 at 11 25 13" src="https://cloud.githubusercontent.com/assets/4273115/17696093/22fd7ae8-63a4-11e6-930d-366c882ebcdf.png">

expected
<img width="259" alt="screen shot 2016-08-16 at 11 25 37" src="https://cloud.githubusercontent.com/assets/4273115/17696099/2cca41f0-63a4-11e6-9f69-3451ec11872e.png">

(As a side note, the first question might need rewording as the background isn't just applied to the code sample)

**Comment by RyanHavoc** [comment]
@EOGreer Should be resolved now. Thanks for reporting it.
