### ISSUE TITLE
Issue with auto-scroll to components based on URL hash

### ISSUE THREAD

**Issue by matt-west** [NoDivide/astrum#59]
#### Tell us about the issue you are experiencing

Astrum is not scrolling to the correct component when the pattern library is visited with a component in the URL hash. This appears to be an issue when testing Astrum with a large number of components and groups.
#### What behaviour would you expect?

Astrum should scroll to the specified component.
#### How can this issue be replicated?

@RyanHavoc Check the pattern library for SBL.
#### Screenshots / Screencast

N/A

**Comment by matt-west** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hkall3hL&#x2F;26-issue-with-auto-scroll-to-components-based-on-url-hash"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue with auto-scroll to components based on URL hash</a>

**Comment by RyanHavoc** [comment]
@matt-west I've added an additional check to ensure the document is ready before triggering the scroll to. This fixes the problem, but not entirely in our case with SBL.

See the bug/59 branch.

The issue we have with SBL is we're loading additional Vue components into the library. Astrum triggers the scrollTo once it's completely loaded. You can see the "Done" on the screenshot below: 

<img width="896" alt="developer tools - http sbl loc pattern-library" src="https://cloud.githubusercontent.com/assets/824169/18255871/05e51b34-73a6-11e6-94b9-4954d6c2e8a0.png">

Then additional components render after they hit the endpoints which throws off the viewing position after it's been scrolled to.

I can't think how we could work around this. It's a bit of an edge case for us mind...

**Comment by matt-west** [comment]
@RyanHavoc I agree that this is an edge case. Happy to go with the solution you've put together.
