### ISSUE TITLE
Code sample still showing when setting to disable_code_sample to true

### ISSUE THREAD

**Issue by dlewand691** [NoDivide/astrum#61]
Code sample alert is still appearing after I've set `"disable_code_sample": true`. Expecting it to hide code sample and alert.

<img width="366" alt="screen shot 2016-08-19 at 12 51 51 pm" src="https://cloud.githubusercontent.com/assets/1159913/17817299/c6e57516-660b-11e6-9b8b-432ecd77a6a0.png">
<img width="1239" alt="screen shot 2016-08-19 at 12 52 05 pm" src="https://cloud.githubusercontent.com/assets/1159913/17817300/c6ee2b3e-660b-11e6-8997-7a27bd56c0aa.png">

**Comment by RyanHavoc** [comment]
The `disable_code_sample` option removes the toggleable code sample from a component preview leaving you with just the rendered component.

It doesn't disable this helper alert message.

**Comment by dlewand691** [comment]
Ah! Is there a way to hide the sample and toggle all together? I'm creating an "Overview" section for each area and don't want to show the toggle/sample.

**Comment by RyanHavoc** [comment]
I'm not sure what you mean... Are you asking if there's a way to hide a sample entirely? No would be the answer to that.

**Comment by dlewand691** [comment]
Yes, I'd like to fully disable the sample. I guess turning off the code sample and putting an empty tag in the markup.html might work.

**Comment by RyanHavoc** [comment]
For what reason do you want to disable the component?

**Comment by alex-ketch** [comment]
@dlewand691 If never need to show the rendered output of the hidden code samples, you can add this to your CSS.
You will still need to add some code or message, otherwise you will get help text telling you to add component markup.

```CSS
.ndpl-component__sample--disabled-code,
.ndpl-component__sample-hidden.ndpl-info {
  display: none;
}
```
