### ISSUE TITLE
Using Foundation framework

### ISSUE THREAD

**Issue by dlewand691** [NoDivide/astrum#63]
I'm trying to use the Foundation framework and getting this error:
`Uncaught TypeError: $(...).foundation is not a function, app-min.js:1`

It requires jQuery to run properly and have edited the index.html file with `<script src="/js/jquery.js"></script>` up top in the `<head>` to load jQuery first. Found this solution from previous issues.

The JS file with the Foundation call uses this on the first  line:
`$(document).foundation();`

Any thoughts on a solution to get it load properly?

**Comment by RyanHavoc** [comment]
Can you not just include jQuery as a JS asset prior to loading Foundation?

**Comment by dlewand691** [comment]
I'm an idiot... I'm using Codekit to compile the JS and didn't include the right scripts. Geez! Nevermind, all fixed! Sometimes you just need a little kick in the pants :-) 👍
