### ISSUE TITLE
Syntax highlighting for code snippets on Pages and component descriptions

### ISSUE THREAD

**Issue by alex-ketch** [NoDivide/astrum#65]
First of all thank you for such an amazing tool!
I would like to make a feature proposal:

#### Tell us about the issue you are experiencing
Code syntax highlighting does only applies to snippets below components, but not to code blocks present in component descriptions or individual pages.

#### What behaviour would you expect?
Code syntax should be coloured for all `pre code`  blocks.

#### How can this issue be replicated?
Insert a code block in any of the markdown files such as a component `description.md` or pages/intro.md`

An example, please remove the trailing slash as it's there to prevent the backticks being stripped by GitHub:

```
```CSS
.cf:before,
.cf:after {
    content: " ";
    display: table;
}

.cf:after {
    clear: both;
}

/**
 * For IE 6/7 only
 * Include this rule to trigger hasLayout and contain floats.
 */
.cf {
    *zoom: 1;
}
``` /
```

#### Screenshot of current result
![screen shot 2016-09-03 at 22 05 06](https://cloud.githubusercontent.com/assets/1646307/18228584/31a03d32-7223-11e6-85dd-6c43c945a400.png)

**Comment by NonPolynomial** [comment]
Hey @alex-ketch ,

astrum uses [highlight.js](https://highlightjs.org/), so highlighting is included.
what you can do is add a file in app/js (e.g. highlighting.js):

```js
'use strict';
document.addEventListener('DOMNodeInserted', function(e) {
    var snippets = Array.prototype.slice.call(document.querySelectorAll('pre code'),0);
    var block;
    if(e.target.nodeType === 1) {
        if(snippets.indexOf(e.target) !== -1) {
            block = e.target;
        } else if(e.target.tagName && e.target.tagName.toLowerCase() === 'pre') {
            e.target.className = e.target.className + ' hljs';
            block = e.target.children[0]
        }
    }
    if(block) {
        hljs.highlightBlock(block);
    }
});
```

and add this file to the assets in `data.json`:
```json
"assets": {
    "js": [
        "app/js/highlighting.js"
    ]
},
```

in your `data.json` you can than define a highlight.js theme (e.g. `tomorrow-night` and disable the background-color overwrite: 
```json
"theme": {
    "code_highlight_theme": "tomorrow-night",
    "override_code_highlight_bg": null,
},
```

hope, i could help.

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;V785h7Ty&#x2F;27-add-facility-to-apply-syntax-highlighting-to-pages-and-component-descriptions"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add facility to apply syntax highlighting to pages and component descriptions.</a>

**Comment by RyanHavoc** [comment]
@alex-ketch I've just added syntax highlighting support to pages and component descriptions in the latest release 1.8.0.

**Comment by munroAllie** [comment]
@RyanHavoc Your solution above worked but only when I called the script in the header of the index.html. For some reason when I called it in the data.json, the **DOMNodeInserted** never fired.

i see above you added this support for version 1.8, I am running version 1.9.5 and I had to use your fix manually.
