### ISSUE TITLE
UX Issue - hyperlinks hard to distinguish  

### ISSUE THREAD

**Issue by henwen** [NoDivide/astrum#72]
Since the text color for `<a>` text is just a darker dark gray than the `<p>` text, my pattern library users (myself included) are having trouble easily noticing hyperlinks in the Component/Page descriptions. 

I think setting `<a>` tags to an accent color (possibly a user-definable one) would be an easy fix.

**Comment by matt-west** [comment]
Thanks @henwen. I agree with your suggestion. I'll get this fixed.

**Comment by matt-west** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EZJwGF9V&#x2F;28-ux-issue-hyperlinks-hard-to-distinguish"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> UX Issue - hyperlinks hard to distinguish</a>
