### ISSUE TITLE
Error in astrum/manager/utils.js:189 : TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DanDvoracek** [NoDivide/astrum#76]
#### Tell us about the issue you are experiencing
I have the project setup on my laptop and everything is fine. I pushed it to git and pulled it on my main machine, installed astrum (had to sudo it strangely enough), and now, even if the init command works fine (it generates the structure), I can't generate any components with the command line. Here is the error message it throws:

```
$ astrum new test/test
/usr/local/lib/node_modules/astrum/manager/utils.js:189
        return this.$data.groups.findIndex(function(item) {
                                 ^
TypeError: undefined is not a function
    at Object.module.exports.getGroupIndex (/usr/local/lib/node_modules/astrum/manager/utils.js:189:34)
    at Object.module.exports.componentExists (/usr/local/lib/node_modules/astrum/manager/utils.js:389:32)
    at Object.module.exports.validateComponent (/usr/local/lib/node_modules/astrum/manager/utils.js:378:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/astrum/manager/astrum-new.js:38:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

Quite frankly, I'm not sure what to do about it :/

#### What behaviour would you expect?
Well I expected to be able to generate components as I did on my laptop. However some commands seem to not work.

#### Your environment
The only note that seems pertinent here (maybe), is that I usually use homebrew to install the packages I need on my main machine. So maybe there would be something to change regarding some paths or something... But I'm still a bit hesitant every time it comes to those things. My laptop config is a bit more anarchic than that I'm afraid, but it works.

Platform (of m main machine):
OS Version:
* Yosemite 10.10.5
Node Version:
* v0.12.7
NPM Version:
* 2.11.3
Astrum Version:
Latest commit 446702e  10 days ago

Any hint is welcome, many thanks in advance!

**Comment by DanDvoracek** [comment]
Sorry I didn't see this was a duplicate of #60 . I have been searching the wrong keywords!

Anyway I had to actually grab the version of node (here https://nodejs.org/en/) as it didn't want to update properly with brew node install.. Anyway, I have been able to update npm with homebrew and node this way.. Now it all works well!

Again, sorry for the duplicate. You can safely close this post when you see it. Thanks again for this sweet tool!

**Comment by alex-ketch** [comment]
@DanDvoracek Glad you figured it out, I would highly recommend using [NVM](https://github.com/creationix/nvm) to avoid future headaches and more flexibility :)

**Comment by DanDvoracek** [comment]
Thanks for the hint, I'll keep it in mind ;)
