### ISSUE TITLE
Can't index.html to show

### ISSUE THREAD

**Issue by luvmex** [NoDivide/astrum#8]
Finish the Getting Start step,
then open index.html file saw the loading and will run forever.

Try to deploy to Firebase will get error deploy.

Is there anyway to show in the browser?

open console get this four errror.
Failed to load resource: net::ERR_FILE_NOT_FOUND
vue-resource.min.js:7 XMLHttpRequest cannot load file:///Users/zhengyen.hsieh/GitHub/Astrum/pattern-library/data.json?cb=Mon%20Jul%2004%202016%2015:41:38%20GMT+0800%20(CST). Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.(anonymous function) @ vue-resource.min.js:7
undefined:1 Uncaught (in promise) Object
main.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by matt-west** [comment]
Hi @luvmex, You will need to run Astrum through a web server as it relies on AJAX requests to load components, which are restricted when serving files directly from your hard drive.

Running Astrum through a local development environment like [Homestead](https://laravel.com/docs/5.2/homestead), [MAMP](https://www.mamp.info/en/), or [XAMPP](https://www.apachefriends.org/index.html) will solve this issue.

**Comment by thierryskoda** [comment]
Hi, I had the same error as @luvmex and I tried to fix the issue by creating a node server that is rendering the index.html in pattern-library.

Now I have the error : ```main.min.js:1 Uncaught SyntaxError: Unexpected token < ```   in the console of my browser.

Do you have any idea what could cause this?

Thank you very much!
Thierry
