### ISSUE TITLE
Astrum with Rails Asset Pipeline

### ISSUE THREAD

**Issue by alexandra-aas** [NoDivide/astrum#80]
#### Tell us about the issue you are experiencing

Astrum uses the stylesheets from the live site to style the pattern library. But with Rails, the asset pipeline fingerprints the stylesheet, so the url won't be the same everytime ([see documentation here](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark)). I'm wondering what the best way is to make the asset pipeline work with the `data.json` file.

**Comment by matt-west** [comment]
Hi @alexandra-aas,

Looks like Rails used to create non-fingerprinted assets too but this was removed in Rails 4. Take look at this article. It contains some approaches for accessing non-fingerprinted assets which could then be specified in Astrums `data.json` file.
https://bibwild.wordpress.com/2014/10/02/non-digested-asset-names-in-rails-4-your-options/

**Comment by alexandra-aas** [comment]
@matt-west I fixed this by using the gem `non-stupid-digest-assets`.

**Comment by matt-west** [comment]
@alexandra-aas Thanks for letting us know. Glad you got it sorted.
