### ISSUE TITLE
No astrum-config.json file found in project root

### ISSUE THREAD

**Issue by elanschnider** [NoDivide/astrum#83]
Can add a component the first time I use astrum fine. But when I close terminal and go back and try add a component, I get the following message: "No astrum-config.json file found in project root"

Any idea?

**Comment by matt-west** [comment]
Hi @elanschnider,

Are you running the astrum command from the same directory that contains the `astrum-config.json` file?

**Comment by elanschnider** [comment]
Ah, no that was my problem. Though that the "init" could be run globally and that the config file would be put in the astrum directory. 


All sorted and working now!

**Comment by matt-west** [comment]
@elanschnider Glad to hear you're up and running again. :)
