### ISSUE TITLE
[FEATURE REQUEST] Different Code Blocks

### ISSUE THREAD

**Issue by davidhellmann** [NoDivide/astrum#84]
Lovely Astrum!

One thing I miss is different Code Blocks. One for the executed part and another one (or more) to add the raw code. Example

c-button.twig 
```
{#
  _c-section.twig
  --------------------------------------------------
#}

{% set defaults = {
  'class': 'c-section',
  'component': '',
  'options': {
    'color': '',
    'size': '',
  },
} %}



{# Merge Options with Defaults #}

{% if attr %}
  {% set attr = defaults|merge(attr) %}
{% else %}
  {% set attr = defaults %}
{% endif %}



<div class="{{ attr.class }}  {{ attr.component }}  {% for option in attr.options %}  {{ option }}  {% endfor %}">

  <div class="c-section__inner">
    {% block sectionContent %}

    {% endblock %}
  </div>

</div>
```

The rendered HTML is another one as the part in the templates. It would be nice to have both. Sure, I can do this within the .md file but a downside here is, that the page become longer and longer. Maybe you've stuff like this in the pipeline :)

Cheers!

**Comment by matt-west** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for preview.html file that overrides markup.html allowing template languages to be used in the markup file.](https://trello.com/c/SYgMlcUG/2-add-support-for-preview-html-file-that-overrides-markup-html-allowing-template-languages-to-be-used-in-the-markup-file)

**Comment by matt-west** [comment]
@davidhellmann Thanks for the suggestion. We’ve had a few similar requests and this is currently on our roadmap here: https://trello.com/c/SYgMlcUG/2-add-support-for-preview-html-file-that-overrides-markup-html-allowing-template-languages-to-be-used-in-the-markup-file

No timescales for when this might be available just yet but it’s on our radar.
