### ISSUE TITLE
Is there a way to create a sub group? 

### ISSUE THREAD

**Issue by elanschnider** [NoDivide/astrum#86]
#### Tell us about the issue you are experiencing

Is there a way to create a sub group? 

Something like:

Branding > colors > primary colors

#### Your environment

Platform:
OS Version:
Node Version:
NPM Version:
Astrum Version:

**Comment by RyanHavoc** [comment]
@elanschnider Not presently, it has been proposed on the development roadmap though. We're monitoring the demand of it.

**Comment by elanschnider** [comment]
Awesome. Thanks
