### ISSUE TITLE
Header title not overridable

### ISSUE THREAD

**Issue by laitine** [NoDivide/astrum#88]
#### Tell us about the issue you are experiencing

When viewing on mobile the header title appears and is not overridable.

#### What behaviour would you expect?

The header title should be listed included in data.json or map to one of the current titles listed in data.json.

#### Screenshots / Screencast

![pattern_library_header_title](https://cloud.githubusercontent.com/assets/305975/20387702/1676efc4-acca-11e6-8418-6f88481d9b49.png)

**Comment by RyanHavoc** [comment]
@laitine Yes I agree. It would be good to be able to set this in the data.json file. We'll add it to the list for the next release.

**Comment by laitine** [comment]
Great. Thanks!

**Comment by RyanHavoc** [comment]
@laitine This has been resolved in version 1.9.2.
