### ISSUE TITLE
Error opening OpenSans from google

### ISSUE THREAD

**Issue by NicoMai** [NoDivide/astrum#9]
Failed to load resource: Die angeforderte URL wurde auf diesem Server nicht gefunden.
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel='stylesheet' type='text/css'>

**Comment by RyanHavoc** [comment]
Hi @NicoMai. Please could you provide us with any further information? What browser are you using? What OS are you on? Do you have the library anywhere public that we can access?

**Comment by NicoMai** [comment]
Hey. I'm using Safari under OSX 10.12 Sierra. I have a very simple fix that i want to pull. At the moment i have no permission for that.

**Comment by RyanHavoc** [comment]
@NicoMai OK. If you fork the repo and submit a pull request we can review your fix. Thanks.
