### ISSUE TITLE
Auto sample hiding is not working.

### ISSUE THREAD

**Issue by RyanHavoc** [NoDivide/astrum#90]
#### Tell us about the issue you are experiencing
When resizing the browser, components that should show a "hidden at this resolution" message are not being hidden.

#### What behaviour would you expect?
Message should appear as Astrum detects that the component is hidden or not.

#### How can this issue be replicated?
Create a component that is hidden on mobile but visible on desktop. Resize the browser.

#### Screenshots / Screencast
N/A

#### Your environment

Platform: OSX
OS Version: 10.11.6
Node Version: 6.7.0
NPM Version: 3.10.3
Astrum Version: 1.8.1

**Comment by Oxicode** [comment]
Me too
