### ISSUE TITLE
Demo style guide not currently working. Showing vue.js error in console

### ISSUE THREAD

**Issue by paulstone** [NoDivide/astrum#95]
#### Tell us about the issue you are experiencing
[http://astrum.nodividestudio.com/pattern-library/](http://astrum.nodividestudio.com/pattern-library/) not currently working. Blank white screen is shown instead. Error in browser console is:

`Uncaught TypeError: Cannot read property 'prototype' of undefined at patch (main.min.js:655)`

#### What behaviour would you expect?
The demo styleguide to be shown.

#### How can this issue be replicated?
Visit [http://astrum.nodividestudio.com/pattern-library/](http://astrum.nodividestudio.com/pattern-library/) and check the console.

#### Screenshots / Screencast
None provided.

#### Your environment
Not applicable probably, but I'm using Mac OS 10.12.3 and just using a web browser (same results in Chrome and Safari).

**Comment by RyanHavoc** [comment]
@paulstone Thanks for the heads up. Fixed now.

**Comment by paulstone** [comment]
Thanks for fixing so quickly @RyanHavoc :)
